apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: loki
  namespace: monitoring
spec:
  interval: 10m
  chart:
    spec:
      chart: loki
      version: "6.4.1"
      sourceRef:
        kind: HelmRepository
        name: grafana
      interval: 5m
  values:
    deploymentMode: "SingleBinary"

    loki:
      auth_enabled: false
      commonConfig:
        replication_factor: 1
      storage:
        type: filesystem

    # Ensure other components are disabled
    backend: {}
    read: {}
    write: {}

    # Configure singleBinary explicitly
    singleBinary:
      replicas: 1
      persistence:
        enabled: true
        size: 1Gi
