apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: loki
  namespace: monitoring
spec:
  interval: 10m
  chart:
    spec:
      chart: loki
      sourceRef:
        kind: HelmRepository
        name: grafana
      interval: 5m
  values:
    loki:
      auth_enabled: false
      commonConfig:
        replication_factor: 1
      storage:
        type: filesystem
    # Single binary configuration
    singleBinary:
      enabled: true
      replicas: 1
    # Disable other components to avoid conflicts
    backend:
      enabled: false
    read:
      enabled: false
    write:
      enabled: false
    # Alternative approach: use simpleScalable mode with single replica
    deploymentMode: SingleBinary
