apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: loki
  namespace: monitoring
spec:
  interval: 10m
  chart:
    spec:
      chart: loki
      version: "6.4.1"  # Pin to a stable version that works with SingleBinary
      sourceRef:
        kind: HelmRepository
        name: grafana
      interval: 5m
  values:
    deploymentMode: SingleBinary

    loki:
      auth_enabled: false
      commonConfig:
        replication_factor: 1
      storage:
        type: filesystem

    # Only enable singleBinary, disable everything else explicitly
    singleBinary:
      enabled: true
      replicas: 1

    # Explicitly disable other modes to avoid conflicts
    backend:
      enabled: false
    read:
      enabled: false
    write:
      enabled: false
    gateway:
      enabled: false
    chunksCache:
      enabled: false
    resultsCache:
      enabled: false
