apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: loki
  namespace: monitoring
spec:
  interval: 10m
  chart:
    spec:
      chart: loki
      version: "5.3.2"
      sourceRef:
        kind: HelmRepository
        name: grafana
      interval: 5m
  values:
    # Use the stable SingleBinary mode configuration
    deploymentMode: SingleBinary

    # Loki server configuration
    loki:
      auth_enabled: false
      commonConfig:
        replication_factor: 1
      storage:
        type: filesystem
      # Schema configuration for Loki
      schemaConfig:
        configs:
        - from: "2024-01-01"
          store: tsdb
          object_store: filesystem
          schema: v13
          index:
            prefix: loki_index_
            period: 24h

    # Explicitly disable other modes to prevent conflicts
    backend: {}
    read: {}
    write: {}
    gateway: {}
    test:
      enabled: false

    # Single binary configuration
    singleBinary:
      replicas: 1
      persistence:
        enabled: true
        size: 1Gi
