apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: loki
  namespace: monitoring
spec:
  interval: 10m
  chart:
    spec:
      chart: loki
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: grafana
      interval: 5m
  values:
    # Use SingleBinary with proper configuration to avoid conflicts
    deploymentMode: "SingleBinary"

    # Loki main configuration
    loki:
      auth_enabled: false
      commonConfig:
        replication_factor: 1
      storage:
        type: filesystem
      schemaConfig:
        configs:
        - from: "2024-01-01"
          store: tsdb
          object_store: filesystem
          schema: v13
          index:
            prefix: loki_index_
            period: 24h

    # Only configure singleBinary, don't define other components at all
    singleBinary:
      replicas: 1
      persistence:
        enabled: true
        size: 1Gi
